### ISSUE TITLE
启动错误Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Hanwall** [Hanwall/get_KNOWLEDGE#1]
/Users/admin/workspaces/get_KNOWLEDGE/source/.vuepress/config.js:1
import { defineConfig } as  a from 'vuepress/config'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at loadConfig (/Users/admin/.config/yarn/global/node_modules/@vuepress/core/lib/node/loadConfig.js:37:18)
    at App.resolveConfigAndInitialize (/Users/admin/.config/yarn/global/node_modules/@vuepress/core/lib/node/App.js:64:30)
    at App.process (/Users/admin/.config/yarn/global/node_modules/@vuepress/core/lib/node/App.js:103:16)
    at dev (/Users/admin/.config/yarn/global/node_modules/@vuepress/core/lib/index.js:17:13)
    at /Users/admin/.config/yarn/global/node_modules/vuepress/lib/util.js:35:12
    at CAC.<anonymous> (/Users/admin/.config/yarn/global/node_modules/vuepress/lib/registerCoreCommands.js:38:23)
    at CAC.runMatchedCommand (/Users/admin/.config/yarn/global/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/Users/admin/.config/yarn/global/node_modules/cac/dist/index.js:541:12)
    at CLI (/Users/admin/.config/yarn/global/node_modules/vuepress/lib/util.js:23:7)

**Comment by Hanwall** [comment]
js files and ts files 的不同，不能导入

**Comment by Hanwall** [comment]
一般是配置错误导致的语法错误

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
t0thkr1s, @syedhali, @shaojunyang, @mybestcool, @cnydo, @dgrr, @ChaoticCrypto, @louiszgm, @rnyn, @eagle453, @ch3rub1m, @prestonhunter, @imjdl, @askiebaby, @bing2008, @killeder, @ttbowen, @kodycode, @black2996, @smileymi6, @theLeroy, @tomagoyaky, @robotparty, @kllmctrl, @hurskar, @xiaotiansky, @sunsetyan, @SushritPasupuleti, @adrianmejias, @ylxg12345, @reza35, @rikster, @beetlepig, @amazingandyyy, @damujen, @siemens84cn, @coollineme, @jack-siren, @zhenalexfan, @jiangkai886, @jeskol, @danielblair, @JackTWallace, @KhanShaheb34, @rblaine95, @enayet123, @mohrezani, @nikzaugg, @GordenChoy, @kaykybbboot, @shenzhigang, @franmaranchello, @mujinqi, @mabehiry, @Nahuelito, @HuaxuDuan, @bluenet13, @rjcnitsche, @liulxiang, @Coinward, @chenlexing, @congim, @yidahis, @siddarth7, @viren-proxy, @vinberm, @yinengy, @jaeminChung, @nicoboou, @abdllah2, @boboyuwu, @pmattos, @valinsky, @DeeLMind, @riwala, @cksmct, @AugustFirst, @GuiminChu, @x1957, @fengjw1, @rock-git, @lyledavids, @samwalls, @maczhao, @outdamud, @R-Y-M-R, @navvvidi, @klenty-rajesh, @AldousCheng, @coding364, @muhammad-hamdi, @JoinBelieve, @WahedSlet, @kouzhudong, @bogdanlungu, @vihaankapoor, @wanmaoxian, @mariokandut, @joaozaratehyangl, @nogut0123, @domsteil, @LjtGitHub, @yoshocon, @kevinho, @usattc, @automagicaly, @lanhaolong20161111, @Navissy, @yangpeng-chn, @RockyYan1994, @NagyGeorgeScripps, @louisnelza, @SongShuo, @tianhongce, @yosoyubik, @jaibeer72, @pnshsh, @asiachrispy, @christopher19, @Heribertosgp, @demesvardestin, @Monkpie, @WuCh1k1n, @MichalZalecki, @julian59189, @dsalin, @Brdjx, @guima-seifer, @ritchiejacobs, @greavettey, @kbqncf, @yomajo, @cn0xroot, @HsingPeng, @Keitrina, @jasonz1987, @JSBACH100, @harrytran998, @rmahtab0079, @jakehemmerle, @ncoelho, @ozanh, @tuxthepenguin84, @HunterHeston, @KyleTang, @caterpillar, @271264921, @hu2013953589
